services:
  tailscale:
    image: tailscale/tailscale:latest
    hostname: tailscale
    environment:
      - TS_AUTHKEY=
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ./tailscale:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
    network_mode: host
  tcp:
    build: 
      context: ./tcp
      dockerfile: Dockerfile
    volumes:
      - ./tcp/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    network_mode: host
    restart: always
    depends_on:
      - tailscale
  udp:
    build: 
      context: ./udp
      dockerfile: Dockerfile
    volumes:
      - ./udp/nginx.conf:/etc/nginx/nginx.conf
    network_mode: host
    restart: always
    depends_on:
      - tailscale
